# Generated by Django 5.0.3 on 2024-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="randomfield",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("1", "Full time"), ("2", "Part time"), ("3", "Internship")],
                max_length=9,
                null=True,
            ),
        ),
    ]
